# Generated by Django 5.2.1 on 2025-05-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiratorizawa', '0002_galleryimage_imagem_alter_galleryimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
