# Generated by Django 5.2.1 on 2025-05-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiratorizawa', '0003_alter_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
