# Generated by Django 5.2.1 on 2025-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiratorizawa', '0004_alter_galleryimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='confirmed_fans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_oponentes/'),
        ),
    ]
